#include <ncurses.h>
#include "colors.h"

#define COLORS_PAIR_BLACK   1
#define COLORS_PAIR_RED     2
#define COLORS_PAIR_GREEN   3
#define COLORS_PAIR_YELLOW  4
#define COLORS_PAIR_BLUE    5
#define COLORS_PAIR_MAGENTA 6
#define COLORS_PAIR_CYAN    7
#define COLORS_PAIR_WHITE   8

const NCURSES_PAIRS_T COLORS_BLACK   = COLOR_PAIR(COLORS_PAIR_BLACK);
const NCURSES_PAIRS_T COLORS_RED     = COLOR_PAIR(COLORS_PAIR_RED);
const NCURSES_PAIRS_T COLORS_GREEN   = COLOR_PAIR(COLORS_PAIR_GREEN);
const NCURSES_PAIRS_T COLORS_YELLOW  = COLOR_PAIR(COLORS_PAIR_YELLOW);
const NCURSES_PAIRS_T COLORS_BLUE    = COLOR_PAIR(COLORS_PAIR_BLUE);
const NCURSES_PAIRS_T COLORS_MAGENTA = COLOR_PAIR(COLORS_PAIR_MAGENTA);
const NCURSES_PAIRS_T COLORS_CYAN    = COLOR_PAIR(COLORS_PAIR_CYAN);
const NCURSES_PAIRS_T COLORS_WHITE   = COLOR_PAIR(COLORS_PAIR_WHITE);

void colors_init() {
    /* Initialize all the colors */
    start_color();

    init_pair(COLORS_PAIR_BLACK,   COLOR_BLACK,   COLOR_BLACK);
    init_pair(COLORS_PAIR_RED,     COLOR_RED,     COLOR_BLACK);
    init_pair(COLORS_PAIR_GREEN,   COLOR_GREEN,   COLOR_BLACK);
    init_pair(COLORS_PAIR_YELLOW,  COLOR_YELLOW,  COLOR_BLACK);
    init_pair(COLORS_PAIR_BLUE,    COLOR_BLUE,    COLOR_BLACK);
    init_pair(COLORS_PAIR_MAGENTA, COLOR_MAGENTA, COLOR_BLACK);
    init_pair(COLORS_PAIR_CYAN,    COLOR_CYAN,    COLOR_BLACK);
    init_pair(COLORS_PAIR_WHITE,   COLOR_WHITE,   COLOR_BLACK);
}
